env:
  commonjs: true
  es6: true
  node: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-console: off
  func-names: off
  import/no-extraneous-dependencies: off
  global-require: off
  no-template-curly-in-string: off
  no-plusplus: off
  # to avoid windows vs unix conflicts
  linebreak-style: off
